# Generated by Django 4.1.2 on 2022-11-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('tasks', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockname', models.CharField(max_length=60)),
                ('blocksize', models.IntegerField()),
                ('crop', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('numberofridges', models.IntegerField()),
                ('blockmanager', models.CharField(max_length=100)),
                ('obstacles', models.CharField(max_length=100)),
                ('sizeofobstacles', models.FloatField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmname', models.CharField(blank=True, max_length=100)),
                ('blocks', models.IntegerField()),
                ('crop', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('hectares', models.IntegerField()),
                ('cropseason', models.CharField(max_length=100)),
                ('particulars', models.CharField(max_length=200)),
                ('productbrand', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('units', models.IntegerField()),
                ('rates', models.FloatField()),
                ('totalcost', models.FloatField()),
            ],
        ),
    ]
