# Generated by Django 4.1.2 on 2022-11-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Creator'), ('FARMER', 'Farmer')], max_length=30),
        ),
    ]
